import Head from "next/head";
import React from "react";
import { Toaster } from "react-hot-toast";
import NextNProgress from "nextjs-progressbar";
import Loading from "./modals/Loading";
import Login from "./modals/Login";
import Register from "./modals/Register";

const nextProgressOptions = {
  color: "#fbbf24",
  showOnShallow: true,
  options: {
    showSpinner: false,
  },
};

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>UA You Mapbox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative bg-slate-400 h-screen w-screen overflow-hidden">
        <NextNProgress {...nextProgressOptions} />
        <Toaster position="top-center" />
        <Loading />
        <Login />
        <Register />
        {children}
      </div>
    </>
  );
};

export default Layout;
